trigger:
  branches:
    include:
      - main  # Replace with the branch you want to track (e.g., main or master)
      - dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  clean: true  # Clears the workspace to ensure the latest changes

- script: |
    git pull origin main  # Pulls the latest from GitHub; adjust for branch
  displayName: 'Pull Latest Changes from GitHub'

schedules:
- cron: "0 */2 * * *"  # Adjust the schedule as needed (this example runs every 2 hours)
  displayName: "Scheduled Pull"
  branches:
    include:
      - main

